## 错误处理,调试和编写

在程序运行中我们可能会遇到这样或那样做那样的问题.

-   由于本身编写遇到的问题  -->  `bug` 
-   由于用户输入不规范  --> 可以编写检查用户输入的代码处理
-   由于各种外部物理因素,如网络突然断掉,磁盘满了  --> `异常` 



### 1.错误处理

` Python` 这样的高级函数内置了 `try` `except ` `finally` `else` 来帮助我们处理错误

但我们还可以利用` Python` 中其他内置函数来更好地处理这样的错误.

#### 记录错误

`logging` 模块就可以十分容易地记录各种错误,例:

```python
import logging
def foo(num):
    return 10 / int(num)
def main():
    try:
        foo('0')
    except Exception as e:
        logging.exception(e)

main()
print('END')

'''现在我们运行一下它'''
>>>ERROR:root:division by zero # loggingy 已经捕获到错误信息
   Traceback......
END #虽然错误产生了,但 logging 打印完错误后还是会正常执行下一个程序的
```



#### 抛出错误

在使用 `try` `except` 时遇到错误时,不仅仅希望能记录错误,还希望系统能直接像 **调用错误栈** 一样为我们返回这个错误,好让我们能跟踪错误而直接处理它,这是我们就需要用到 ` raise` 将错误抛出



### 2.调试

我们有几种调试方法:

1.  使用 `print` 将有可能有问题的变量打印出来看看

    >   优点:简单有效
    >
    >   缺点:最后需要手动删除 `print` ,比较麻烦

2.  使用 `assert` 断言代替 `print`,例 

    ```python
    def foo(s):
        n = int(s)
        assert n != 0, 'n is zero!'
        return 10 / n
    
    def main():
        foo('0')
        pass
    
    '''现在我们运行看看'''
    >>>main()
    >>>Traceback...
    AssertionError #如果断言 n == 0 时会抛出 AssertionError 错误
    ```

    >   优点:
    >
    >   1.  返回的错误解释信息可定制,让我们可以地一目了然地发现哪里发生了错误
    >   2.  我们可以在 `python` 解释器中多输入 `-o` 以形成 `python -o file_name.py` 来关闭 `assert` 
    >
    >   缺点:这仅能检查含参数少的变量,或看一个变量类型是否符合要求



3.  `logging`

    我们可以利用 `logging ` 记录错误的特性, 用与调试

    让我们来看看

    ```python
    import logging
    logging.basicConfig(level=logging.INFO) #指定输出 level 为 INFO 的错误
    n = 0
    logging.info('n = %d' % n) #如 level 与上式匹配,输出错误
    print(10 / n)
    
    '''现在我们来看看它到底有多少能耐'''
    >>>INFO:root:n = 0 #多了root, 注意level设定为这个错误级别后,无论出不出现错误,logging都会调出root
    Traceback (most recent call last):
        .....
    ```

    >   优点:
    >
    >   1. 能按照 level 定向抛出`root`错误, 故而你可以放心地输出不同级别的信息，也不用删除，最后统一控制输出哪个级别的信息
    >
    >    3.  由于其还能记录错误,我们还可以在抛出错误的同时记录错误到指定的文件中,方便后续处理
    >
    >   缺点:并不是专门的用于调试的模块
    >

    

4.  IDE

使用 IDE 软件畅快地设置 **断点** 并 **单步调试**





### 3.单元测试

>    单元测试是用来对一个模块、一个函数或者一个类来进行正确性检验的测试工作 

例:

```python
'''现在我们针对 abs 这个内建函数进行测试'''
import unittest
class Test(unittest.TestCase):
    def test_do_it(self): #如果不以test开头的方法,则库函数不会对该函数进行检查
        self.assertEqual(abs(-1),1) 
        
        self.assertTrue(isinstance(abs(-1),int))
        
        with self.assertRaises(TypeError): #观察当出错时是否是 TypeError 错误
            abs('1')
     pass
'''启动该函数也需要引用该函数库'''
unittest.main()
```





### 4.文档测试

>   利用 `doctest` 模块可以直接提取注释中的代码并执行测试 

例:

```Python
'''
>>> f = abs
>>> f(-1)
1
>>> f(0)
0 
'''
import doctest #这个import仅能在 doctest.testmod()前
doctest.testmod()

'''现在我们开始运行下'''
>>> #什么输出都没,说明运行正确
```

